export function Footer() {
  return (
    <footer className="py-4 mt-auto">
      <div className="max-w-3xl mx-auto px-4 text-center text-sm text-gray-500">
        © 2025 powered by Bob.one, All content generated by AI。
      </div>
    </footer>
  );
} 